### ISSUE TITLE
Missing command to generate boot.scr on Raspberry Pi

### ISSUE THREAD

**Issue by hyos** [ros-realtime/reference-system#64]
The [Isolate CPUs](https://github.com/ros-realtime/reference-system#isolate-cpus) section of README.md is currently missing a `mkimage` command to convert boot.script to boot.scr. So I suggest adding:
```
# generate boot.scr
mkimage -A arm64 -O linux -T script -C none -d boot.script boot.scr
```
before `# replace boot.scr`.

**Comment by flynneva** [comment]
@razr or @hyos want to make a PR with this change? I was going to try the `isolate cpus` section later today so this is good info!

**Comment by hyos** [comment]
@flynneva I will do this shortly
